# spring.application.name=gateway

server:
    address:  192.168.1.2
    port: 9094

spring:
    application:
        name: gatewayserver
    cloud:
        gateway:
            discovery:
                locator:
                    enabled: false
                    lowerCaseServiceId: true
eureka:
    instance:
        preferIpAddress: true
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: "http://localhost:9080/eureka/"




management:
    endpoints:
        web:
            exposure:
                include: "*"
            cors:
                allowed-origins: " http://122.169.207.194:9093"
                allowed-methods: "GET,POST,PUT,DELETE"

        